-- Most Frequently Mentioned Hashtags

PREFIX global: <http://example.org/digiscan360/schema#>

SELECT ?hashtag (COUNT(?tweet) AS ?mention_count)
WHERE {
  ?tweet a global:Tweet ;
         global:hashtags ?hashtags .
  BIND(STRAFTER(?hashtags, "#") AS ?hashtag)
}
GROUP BY ?hashtag
ORDER BY DESC(?mention_count)
LIMIT 10
